# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HD6nAeqN8l-dllBw7Wft39tvvgZA9I3L
"""

import streamlit as st
import pandas as pd

st.title('A Different assignment than the last')

options = {'goodbye', 'hello'}

st.write('Data: Hey there! Say Hello!')

select = ('say hello', options)

selections = st.selectbox('What will you say?', options)

if select == 'hello':
  st.write("Good Job!")
elif select == 'goodbye':
  st.write("That's not Hello")
